export const SLOT_ABI = [
  {
    inputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    constant: false,
    inputs: [],
    name: 'spin',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3dce4920',
  },
  {
    constant: false,
    inputs: [],
    name: 'buyCoins',
    outputs: [{ name: '', type: 'uint256' }],
    payable: true,
    stateMutability: 'payable',
    type: 'function',
    signature: '0x3dce4920',
  },
  {
    constant: false,
    inputs: [],
    name: 'getPrice',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3dce4920',
  },
  {
    constant: false,
    inputs: [],
    name: 'getCoins',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3dce4920',
  },
];
